language: java

jdk:
  - openjdk10

os:
  - linux

before_install:
  - chmod +x gradlew


branches:
  only:
    - master

cache:
  directories:
    - $HOME/.gradle

install: true

script:
  - ./gradlew clean build
